version: '3.8'

services:
  database:
    image: postgres
    container_name: 'jwt-auth-db'
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker-user
      - POSTGRES_PASSWORD=docker-pass
      - POSTGRES_DB=docker-db
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: 'jwt-auth-app'
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    # driver: local
