version: '3.8'

services:
  postgres:
    image: postgres
    container_name: 'jwt-auth-db'
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker-user
      - POSTGRES_PASSWORD=docker-pass
      - POSTGRES_DB=docker-db
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis
    container_name: 'jwt-auth-redis'
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass docker-redis-pass
    volumes:
      - redisdata:/data/redis

  app:
    build: .
    container_name: 'jwt-auth-app'
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/usr/app

volumes:
  pgdata:
  redisdata:
